apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mysql-helm
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql-server
  namespace: mysql
spec:
  interval: 10m
  chart:
    spec:
      chart: mysql
      sourceRef:
        kind: HelmRepository
        name: mysql-helm
        namespace: flux-system
      interval: 1m
