apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: mysql
  namespace: flux-system
spec:
  interval: 10m
  url: oci://registry-1.docker.io/bitnamicharts/mysql
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql
  namespace: mysql
spec:
  interval: 10m
  releaseName: mysql
  chartRef:
    kind: OCIRepository
    name: mysql
    namespace: flux-system
