apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partition-medium
spec:
  action: partition
  mode: all
  selector:
    labelSelectors:
      "app": "nginx"
  direction: to
  target:
    selector:
      labelSelectors:
        "app": "httpd"
    mode: all
  duration: "50s"
  scheduler:
    cron: "@every 1m"
