apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nvdia-gpu-operator
  namespace: flux-system
spec:
  interval: 1m
  url: https://helm.ngc.nvidia.com/nvidia/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvdia-gpu-operator
  namespace: nvidia
spec:
  interval: 10m
  chart:
    spec:
      chart: gpu-operator
      version: 'v24.3.0'
      sourceRef:
        kind: HelmRepository
        name: nvdia-gpu-operator
        namespace: flux-system
      interval: 1m
  values:
    driver:
      enabled: true
      version: "550.90.07"
