apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent-buffer
  namespace: monitoring
spec:
  selectAllByDefault: false
  remoteWrite:
    - url: "http://vminsert-cluster-1.monitoring.svc:8480/insert/0/prometheus/api/v1/write"
    - url: "http://vminsert-cluster-2.monitoring.svc:8480/insert/0/prometheus/api/v1/write"
  vmAgentExternalLabelName: vmagent_ha
  ingestOnlyMode: true
  maxDiskUsage: 1Gi
  replicaCount: 2
  statefulMode: true
  statefulStorage:
    volumeClaimTemplate:
      spec:
        resources:
            requests:
              storage: 2Gi
