apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: cluster-1
  namespace: monitoring
spec:
  retentionPeriod: "1"
  replicationFactor: 1
  vmstorage:
    replicaCount: 2
    storageDataPath: "/vm-data"
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 10Gi
  vmselect:
    replicaCount: 1
    cacheMountPath: "/select-cache"
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 2Gi
  vminsert:
    replicaCount: 2
    resources:
      limits:
        cpu: "1"
        memory: "500Mi"
