# apiVersion: source.toolkit.fluxcd.io/v1
# kind: HelmRepository
# metadata:
#   name: vm
#   namespace: flux-system
# spec:
#   interval: 1m
#   url: https://victoriametrics.github.io/helm-charts
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: vm-operator
#   namespace: monitoring
# spec:
#   interval: 10m
#   install: 
#     createNamespace: true
#   chart:
#     spec:
#       chart: victoria-metrics-operator
#       version: '0.39.1'
#       sourceRef:
#         kind: HelmRepository
#         name: vm
#         namespace: flux-system
#       interval: 1m
