apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluxcd-demo
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: fluxcd-demo
  targetNamespace: fluxcd-demo
  chart:
    git: git@github.com:NotOpss/flux-medium-manifests.git
    path: helm-charts/fluxcd-demo
    ref: fluxcd-demo
