apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name:  nats
  namespace: flux-system
spec:
  interval: 1m
  url: https://nats-io.github.io/k8s/helm/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name:  nats
  namespace: nats
spec:
  interval: 10m
  install:
    createNamespace: true
  chart:
    spec:
      chart:  nats
      version: "*"
      sourceRef:
        kind: HelmRepository
        name:  nats
        namespace: flux-system
      interval: 1m
  values: 
    config:
      cluster:
        enabled: true
      jetstream:
        enabled: true
