apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name:  devtron
  namespace: flux-system
spec:
  interval: 1m
  url: https://helm.devtron.ai
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name:  devtron
  namespace: devtroncd
spec:
  interval: 10m
  install:
    createNamespace: true
  chart:
    spec:
      chart:  devtron
      version: "*"
      sourceRef:
        kind: HelmRepository
        name:  devtron
        namespace: flux-system
      interval: 1m
